 menu98edb85b00d9527ad5acebe451b3fae6 = {     {"7-Zip FM", "7zFM"},
     {"ADesk Bar", "adeskbar", "/usr/share/pixmaps/adeskbar.png" },
     {"Akonaditray", "akonaditray"},
     {"Ark", "ark -caption \"Ark\" "},
     {"Avant Window Navigator", "avant-window-navigator"},
     {"CherryTree", "cherrytree "},
     {"ClamTk", "clamtk ", "/usr/share/pixmaps/clamtk.png" },
     {"Disks", "gnome-disks"},
     {"File Manager PCManFM", "pcmanfm "},
     {"Filelight", "filelight "},
     {"Image Viewer", "gpicview ", "/usr/share/pixmaps/gpicview.png" },
     {"KCalc", "kcalc -caption \"KCalc\""},
     {"KCharSelect", "kcharselect -caption \"KCharSelect\""},
     {"KGpg", "kgpg "},
     {"KTimer", "ktimer"},
     {"KWrite", "kwrite "},
     {"KeePass Password Safe", "keepass"},
     {"Parcellite", "parcellite", "/usr/share/pixmaps/parcellite.png" },
     {"Root Terminal", "gksu -l gnome-terminal", "/usr/share/pixmaps/gksu-root-terminal.png" },
     {"StarDict", "stardict", "/usr/share/pixmaps/stardict.png" },
     {"Sublime Text", "subl "},
     {"Synapse", "synapse"},
     {"Tomboy Notes", "tomboy --search"},
     {"Vi IMproved", "gvim -f ", "/usr/share/pixmaps/gvim.png" },
     {"Xchm", "xchm ", "/usr/share/pixmaps/xchm-48.xpm" },
     {"gedit", "gedit "},
 }

 menu78059f1898ed518c6ccd6a6392fa82c1 = {     {"AUR", "xdg-open https://aur.archlinux.org"},
     {"Bugs", "xdg-open https://bugs.archlinux.org"},
     {"Developers", "xdg-open http://www.archlinux.org/developers/"},
     {"Documentation", "xdg-open https://wiki.archlinux.org/index.php/Official_Arch_Linux_Install_Guide"},
     {"Donate", "xdg-open http://www.archlinux.org/donate/"},
     {"Forum", "xdg-open https://bbs.archlinux.org"},
     {"Homepage", "xdg-open http://www.archlinux.org"},
     {"SVN", "xdg-open http://projects.archlinux.org/svntogit/"},
     {"Schwag", "xdg-open http://www.zazzle.com/archlinux/"},
     {"Wiki", "xdg-open https://wiki.archlinux.org"},
 }

 menude7a22a0c94aa64ba2449e520aa20c99 = {     {"KGeography", "kgeography"},
     {"KStars", "kstars -caption \"KStars\" "},
     {"Stellarium nightsky renderer", "stellarium", "/usr/share/pixmaps/stellarium.png" },
 }

 menu251bd8143891238ecedc306508e29017 = {     {"And Yet It Moves", "steam steam://rungameid/18700"},
     {"Bastion", "steam steam://rungameid/107100", "/usr/share/pixmaps/steam.png" },
     {"Cave Story+", "steam steam://rungameid/200900"},
     {"Chess", "glchess"},
     {"Cogs", "steam steam://rungameid/26500"},
     {"Counter-Strike (Beta)", "steam steam://rungameid/10", "/usr/share/pixmaps/steam.png" },
     {"Counter-Strike Condition Zero (Beta)", "steam steam://rungameid/80", "/usr/share/pixmaps/steam.png" },
     {"Counter-Strike Source", "steam steam://rungameid/240", "/usr/share/pixmaps/steam.png" },
     {"Cubemen", "steam steam://rungameid/207250"},
     {"DEFCON", "steam steam://rungameid/1520"},
     {"DeSmuME (Gtk)", "desmume", "/usr/share/pixmaps/DeSmuME.xpm" },
     {"DeSmuME (Gtk-Glade)", "desmume-glade", "/usr/share/pixmaps/DeSmuME.xpm" },
     {"Desura", "/opt/desura/desura ", "///opt/desura/data/desura.png" },
     {"Desura", "desura"},
     {"Desura (Force Update)", "xterm -e /opt/desura/desura -f", "///opt/desura/data/desura.png" },
     {"FTL Faster Than Light", "steam steam://rungameid/212680", "/usr/share/pixmaps/steam.png" },
     {"Five or More", "glines"},
     {"Four-in-a-Row", "gnect"},
     {"Frozen Synapse", "steam steam://rungameid/98200", "/usr/share/pixmaps/steam.png" },
     {"Iagno", "iagno"},
     {"JPCSP", "jpcsp"},
     {"KSudoku", "ksudoku  -caption \"KSudoku\""},
     {"Killing Floor", "steam steam://rungameid/1250", "/usr/share/pixmaps/steam.png" },
     {"Klotski", "gnotski"},
     {"LIMBO", "steam steam://rungameid/48000", "/usr/share/pixmaps/steam.png" },
     {"Lights Off", "lightsoff"},
     {"Mahjongg", "gnome-mahjongg"},
     {"Minecraft", "minecraft", "///usr/share/pixmaps/minecraft.png" },
     {"Mines", "gnomine"},
     {"Multiwinia", "steam steam://rungameid/1530"},
     {"Nibbles", "gnibbles"},
     {"PyChess", "pychess", "/usr/share/pixmaps/pychess.svg" },
     {"Quadrapassel", "quadrapassel"},
     {"Red Orchestra Ostfront 41-45", "steam steam://rungameid/1200", "/usr/share/pixmaps/steam.png" },
     {"Robots", "gnobots2"},
     {"Serious Sam 3 BFE", "steam steam://rungameid/41070"},
     {"Solar 2", "steam steam://rungameid/97000"},
     {"Space Pirates and Zombies", "steam steam://rungameid/107200"},
     {"Steam", "/usr/bin/steam ", "/usr/share/pixmaps/steam.png" },
     {"Sudoku", "gnome-sudoku"},
     {"Swell Foop", "swell-foop"},
     {"Tali", "gtali"},
     {"Team Fortress 2", "steam steam://rungameid/440"},
     {"Tetravex", "gnotravex"},
     {"The Book of Unwritten Tales The Critter Chronicles Demo", "steam steam://rungameid/226540"},
     {"Trine 2", "steam steam://rungameid/35720", "/usr/share/pixmaps/steam.png" },
     {"World of Goo", "steam steam://rungameid/22000"},
     {"World of Goo Demo", "steam steam://rungameid/22010"},
     {"iBomber Defense Pacific", "steam steam://rungameid/206690"},
 }

 menud334dfcea59127bedfcdbe0a3ee7f494 = {     {"Blender", "blender"},
     {"E-book Viewer", "ebook-viewer ", "/usr/share/pixmaps/calibre-viewer.png" },
     {"Gcolor2", "gcolor2", "///usr/share/pixmaps/gcolor2/icon.png" },
     {"Image Viewer", "gpicview ", "/usr/share/pixmaps/gpicview.png" },
     {"KPhotoAlbum", "kphotoalbum"},
     {"KRuler", "kruler"},
     {"KSnapshot", "ksnapshot -caption \"KSnapshot\""},
     {"Krita", "krita "},
     {"LRF Viewer", "lrfviewer ", "/usr/share/pixmaps/calibre-viewer.png" },
     {"LibreOffice Draw", "libreoffice --draw "},
     {"Okular", "okular   -caption \"Okular\""},
     {"Open in RAW editor", "open-raw.pl "},
     {"feh", "feh ", "///usr/share/feh/images/logo.svg" },
     {"qcomicbook", "qcomicbook", "/usr/share/pixmaps/qcomicbook.png" },
 }

 menuc8205c7636e728d448c2774e6a4a944b = {     {"Akregator", "akregator  -caption \"Akregator\""},
     {"Avahi SSH Server Browser", "/usr/bin/bssh"},
     {"Avahi VNC Server Browser", "/usr/bin/bvnc"},
     {"Chromium", "chromium "},
     {"Deluge", "deluge-gtk ", "/usr/share/pixmaps/deluge.png" },
     {"Dropbox", "dropboxd", "/usr/share/pixmaps/dropbox.png" },
     {"Firefox", "/usr/lib/firefox/firefox "},
     {"Google Chrome", "/opt/google/chrome/google-chrome "},
     {"Google Music Manager", "/opt/google/musicmanager/google-musicmanager"},
     {"Hotot Gtk2", "hotot-gtk2"},
     {"Hotot Gtk3", "hotot-gtk3"},
     {"Hotot Kde", "hotot-kde"},
     {"Hotot Qt", "hotot-qt"},
     {"KTorrent", "ktorrent  -caption \"KTorrent\" "},
     {"KVpnc", "xdg_menu_su kvpnc"},
     {"Liferea", "liferea"},
     {"NixNote", "/usr/share/nixnote/nixnote.sh", "///usr/share/nixnote/nixnote.png" },
     {"Opera", "/usr/bin/opera "},
     {"Pidgin Internet Messenger", "pidgin"},
     {"Remotedesktop Client", "grdesktop", "/usr/share/pixmaps/grdesktop.png" },
     {"Skype", "skype ", "/usr/share/pixmaps/skype.png" },
     {"Steam", "/usr/bin/steam ", "/usr/share/pixmaps/steam.png" },
     {"Vidalia", "vidalia"},
     {"Wicd", "/usr/bin/wicd-client", "/usr/share/pixmaps/wicd-gtk.xpm" },
     {"Zenmap", "zenmap ", "///usr/share/zenmap/pixmaps/zenmap.png" },
     {"Zenmap (as root)", "/usr/share/zenmap/su-to-zenmap.sh ", "///usr/share/zenmap/pixmaps/zenmap.png" },
     {"aLinkCreator", "alc", "/usr/share/pixmaps/alc.xpm" },
     {"aMule", "amule", "/usr/share/pixmaps/amule.xpm" },
     {"aMuleGUI", "amulegui", "/usr/share/pixmaps/amulegui.xpm" },
     {"qBittorrent", "qbittorrent ", "/usr/share/pixmaps/qbittorrent.png" },
     {"wxCas", "wxcas", "/usr/share/pixmaps/wxcas.xpm" },
 }

 menudf814135652a5a308fea15bff37ea284 = {     {"Calibre", "calibre", "/usr/share/pixmaps/calibre-gui.png" },
     {"FBReader", "FBReader ", "/usr/share/pixmaps/FBReader.png" },
     {"LibreOffice", "libreoffice "},
     {"LibreOffice Base", "libreoffice --base "},
     {"LibreOffice Calc", "libreoffice --calc "},
     {"LibreOffice Draw", "libreoffice --draw "},
     {"LibreOffice Impress", "libreoffice --impress "},
     {"LibreOffice Writer", "libreoffice --writer "},
     {"Lokalize", "lokalize  -caption \"Lokalize\""},
     {"Okular", "okular   -caption \"Okular\""},
     {"StarDict", "stardict", "/usr/share/pixmaps/stardict.png" },
     {"ePDFViewer", "epdfview "},
 }

 menu6311ae17c1ee52b36e68aaf4ad066387 = {     {"ARandR", "arandr"},
     {"Adobe Flash Player", "flash-player-properties"},
     {"Awn Settings", "awn-settings"},
     {"Customize Look and Feel", "lxappearance"},
     {"Desktop Preferences", "pcmanfm --desktop-pref"},
     {"Fcitx Config Tool", "fcitx-configtool"},
     {"File Manager", "thunar-settings"},
     {"GTK Styles and Fonts", "kcmshell4 kcmgtk4"},
     {"KDE System Settings", "systemsettings -caption \"KDE System Settings\" "},
     {"NVIDIA X Server Settings", "/usr/bin/nvidia-settings", "///usr/share/pixmaps/nvidia-settings.png" },
     {"Network Connections", "nm-connection-editor"},
     {"Openbox Configuration Manager", "obconf ", "/usr/share/pixmaps/obconf.png" },
     {"Panel tint2", "tint2conf", "/usr/share/pixmaps/tint2conf.png" },
     {"Preferred Applications", "libfm-pref-apps"},
     {"Steam", "env WINEPREFIX=\"/home/elvis/.wine\" wine C:\\\\windows\\\\command\\\\start.exe /Unix /home/elvis/.wine/dosdevices/c:/users/Public/Start\\ Menu/Programs/Steam/Steam.lnk"},
     {"Steam Support Center", "env WINEPREFIX=\"/home/elvis/.wine\" wine C:\\\\windows\\\\command\\\\start.exe /Unix /home/elvis/.wine/dosdevices/c:/users/elvis/Start\\ Menu/Programs/Steam/Steam\\ Support\\ Center.lnk"},
     {"i3", "i3"},
 }

 menue6f43c40ab1c07cd29e4e83e4ef6bf85 = {     {"CMake", "cmake-gui ", "/usr/share/pixmaps/CMakeSetup32.png" },
     {"Geany", "geany "},
     {"Lokalize", "lokalize  -caption \"Lokalize\""},
     {"OpenJDK Monitoring & Management Console", "/usr/bin/jconsole"},
     {"OpenJDK Policy Tool", "/usr/bin/policytool"},
 }

 menu52dd1c847264a75f400961bfb4d1c849 = {     {"Aegisub", "aegisub-3.1 "},
     {"Amarok", "amarok "},
     {"Audacity", "audacity ", "/usr/share/pixmaps/audacity.xpm" },
     {"DeaDBeeF", "deadbeef "},
     {"EasyTAG", "easytag "},
     {"FFADO Mixer", "ffado-mixer"},
     {"Google Music Manager", "/opt/google/musicmanager/google-musicmanager"},
     {"K3b", "k3b "},
     {"MPlayer", "mplayer "},
     {"MuseScore", "mscore", "/usr/share/pixmaps/mscore.png" },
     {"OSD Lyrics", "osdlyrics"},
     {"OpenShot Video Editor", "openshot ", "/usr/share/pixmaps/openshot.svg" },
     {"PNMixer", "pnmixer"},
     {"PulseAudio Volume Control", "pavucontrol"},
     {"QT V4L2 test Utility", "qv4l2"},
     {"SMPlayer", "smplayer "},
     {"Subtitle Editor", "subtitleeditor ", "/usr/share/pixmaps/subtitleeditor.svg" },
     {"Transcoder", "Transcoder", "///usr/share/Transcoder/transcoder.png" },
     {"VLC media player", "/usr/bin/vlc "},
     {"qt-recordMyDesktop", "qt-recordMyDesktop", "/usr/share/pixmaps/qt-recordmydesktop.png" },
 }

 menuee69799670a33f75d45c57d1d1cd0ab3 = {     {"Avahi Zeroconf Browser", "/usr/bin/avahi-discover"},
     {"Bulk Rename", "/usr/lib/Thunar/ThunarBulkRename "},
     {"Dolphin", "dolphin  -caption \"Dolphin\" "},
     {"Fcitx", "fcitx"},
     {"Firestarter", "gksu firestarter", "/usr/share/pixmaps/firestarter.png" },
     {"GParted", " /usr/sbin/gparted "},
     {"GSmartControl", "/usr/bin/gsmartcontrol", "/usr/share/pixmaps/gsmartcontrol.png" },
     {"Htop", "xterm -e htop", "/usr/share/pixmaps/htop.png" },
     {"K3b", "k3b "},
     {"KDiskFree", "kdf -caption \"KDiskFree\""},
     {"KSysGuard", "ksysguard "},
     {"KSystemLog", "xdg_menu_su ksystemlog  -caption \"KSystemLog\""},
     {"KUser", "xdg_menu_su kuser  -caption \"KUser\""},
     {"Konsole", "konsole"},
     {"KwikDisk", "kwikdisk -caption \"KwikDisk\""},
     {"Marlin File Manager", "marlin "},
     {"Nepomuk Backup", "nepomukbackup"},
     {"Nepomuk Cleaner", "nepomukcleaner"},
     {"Nepomuk File Indexing Controller", "nepomukcontroller"},
     {"Oracle VM VirtualBox", "VirtualBox "},
     {"ROX Filer", "rox", "/usr/share/pixmaps/rox.png" },
     {"Sakura", "lilyterm -g 84x21", "/usr/share/pixmaps/terminal-tango.svg" },
     {"Task Manager", "lxtask"},
     {"Terminator", "terminator", "/usr/share/pixmaps/terminator.png" },
     {"Thunar File Manager", "thunar "},
     {"TrueCrypt", "truecrypt", "/usr/share/pixmaps/truecrypt.xpm" },
     {"UNetbootin", "/usr/bin/unetbootin"},
     {"UXTerm", "uxterm", "/usr/share/pixmaps/xterm-color_48x48.xpm" },
     {"Wireshark", "wireshark "},
     {"XSensors", "/usr/bin/xsensors", "///usr/share/pixmaps/xsensors/default.xpm" },
     {"XTerm", "xterm", "/usr/share/pixmaps/xterm-color_48x48.xpm" },
     {"Yakuake", "yakuake"},
     {"dconf Editor", "dconf-editor"},
 }

xdgmenu = {    {"Accessories", menu98edb85b00d9527ad5acebe451b3fae6},
    {"Archlinux", menu78059f1898ed518c6ccd6a6392fa82c1},
    {"Education", menude7a22a0c94aa64ba2449e520aa20c99},
    {"Games", menu251bd8143891238ecedc306508e29017},
    {"Graphics", menud334dfcea59127bedfcdbe0a3ee7f494},
    {"Internet", menuc8205c7636e728d448c2774e6a4a944b},
    {"Office", menudf814135652a5a308fea15bff37ea284},
    {"Other", menu6311ae17c1ee52b36e68aaf4ad066387},
    {"Programming", menue6f43c40ab1c07cd29e4e83e4ef6bf85},
    {"Sound & Video", menu52dd1c847264a75f400961bfb4d1c849},
    {"System Tools", menuee69799670a33f75d45c57d1d1cd0ab3},
}

