#!/bin/bash

get_tarball(){
    curl -k -o $1.tar.gz https://aur.archlinux.org/cgit/aur.git/snapshot/$1.tar.gz&&
	tar xvf $1.tar.gz;
	rm -rf $1.tar.gz;
}

git_message_upg(){
	git add .;
	git commit -m "upgpkg: $1";
}

git_message_add(){
	git add .;
	git commit -m "addpkg: $1";
}

git_message_remove(){
	git rm -rf $1;
	git add --all .;
	git commit -m "remove: $1";
}

while getopts "a:u:r:" opt; do
	case $opt in
		a)
			echo "addpkg: $OPTARG";
			get_tarball $OPTARG;
			git_message_add $OPTARG;
			;;
		u)
			echo "upgpkg: $OPTARG";
			get_tarball $OPTARG;
			git_message_upg $OPTARG;
			;;
		r)
			echo "remove: $OPTARG";
			git_message_remove $OPTARG;
			;;
	esac
done
