#!/bin/bash
case "$1" in
	up)
		case "$2" in
			*)
				echo y|yaourt -G $2&&
				git add .&&
				git commit -m "upgpkg: $2";
				;;
		esac
		;;
	add)
		case "$2" in
			*)
				yaourt -G $2&&
				git add .&&
				git commit -m "addpkg: $2";
				;;
		esac
		;;
	build)
		cd "$2"&&
		archlinuxcn-x86_64-build&&
		archlinuxcn-i686-build&&
		mv *pkg.tar.xz ~/repo;
		;;
esac