#!/bin/bash

get_tarball(){
	curl -o $OPTARG.tar.gz https://aur.archlinux.org/cgit/aur.git/snapshot/$OPTARG.tar.gz&&rm -rf $OPTARG;
	tar xvf $OPTARG.tar.gz;
	rm -rf $OPTARG.tar.gz;
}

git_message_upg(){
	git add .;
	git commit -m "upgpkg: $OPTARG";
}

git_message_add(){
	git add .;
	git commit -m "addpkg: $OPTARG";
}

git_message_remove(){
	git rm -rf $OPTARG;
	git add --all .;
	git commit -m "remove: $OPTARG";
}

while getopts "a:u:r:" opt; do
	case $opt in
		a)
			echo "addpkg: $OPTARG";
			get_tarball $OPTARG;
			git_message_add $OPTARG;
			;;
		u)
			echo "upgpkg: $OPTARG";
			get_tarball $OPTARG;
			git_message_upg $OPTARG;
			;;
		r)
			echo "remove: $OPTARG";
			git_message_remove $OPTARG;
			;;
	esac
done
