#!/bin/bash

if [[ -n $TMUX ]];then
    echo "don't use tmux in tmux."
else
    if [[ `tmux ls|cut -d":" -f1` == 'work' ]];then
        tmux -2 attach;
    else
        name="work"
        cd ~
        tmux new-session -d -s $name -n 0&&
        tmux new-window -t $name:1 -n 1
        tmux new-window -t "$name:2" -n archcn
        tmux split-window -h -p 50
        tmux new-window -t "$name:99"
        tmux split-window -h
        tmux select-pane -L
        tmux split-window -v -p 60
        tmux send-keys -t work:archcn.0 cd\ ~/git/archlinuxcn Enter
        tmux send-keys -t work:archcn.1 cd\ ~/git/archlinuxcn Enter
        tmux send-keys -t work:99.0 !gost Enter
        tmux send-keys -t work:99.1 cd\ ~/Desktop Enter
        tmux send-keys -t work:99.2 ncmpcpp Enter
        tmux select-window -t 0
        tmux attach-session -t $name
    fi
fi
