#!/bin/bash

if [[ `tmux ls|cut -d":" -f1` == work ]];then
    tmux -2 attach;
else
    session_name="work"
    cd ~
    tmux -2 new-session -d -s $session_name -n 0
    #tmux split-window -v
    #tmux split-window -h
    #tmux selectp -U
    #tmux split-window -h
    #tmux selectp -L
    cd ~/git/dotfiles
    tmux new-window -t $session_name:1 -n 1
    tmux split-window -h
    cd ~/git/archlinuxcn
    tmux new-window -t $session_name:2 -n 2
    tmux split-window -h
    cd ~
    tmux new-window -t $session_name:3 -n 3
    tmux split-window -h
    tmux select-window -t $session_name:0
    tmux -2 attach-session -t $session_name
fi
