#!/bin/bash
name="work"
hostname=`hostname`

if [[ -n $TMUX ]];then
    echo "don't use tmux in tmux."
    exit
fi
ret=`tmux ls|grep -E "^work"`
if [[ ${ret} != "" ]];then
    tmux attach-session -t $name
    exit
fi

normal() {
    cd ~
    tmux new-session -d -s $name -n 0
    tmux new-window -t "$name:99"
    tmux select-window -t 0
    tmux attach-session -t $name
}

nas() {
    cd ~
    tmux new-session -d -s $name -n 0
    tmux attach-session -t $name
}

case ${hostname} in
    *nas*)
        nas
        ;;
    *)
        normal
        ;;
esac

